run ts tests for win

diff --git a/.github/workflows/gate.yml b/.github/workflows/gate.yml
--- a/.github/workflows/gate.yml
+++ b/.github/workflows/gate.yml
@@ -29,52 +29,94 @@ jobs:
     - name: Build
       run: dotnet build --configuration Release --no-restore
 
-    - name: Test (4.8)
-      run: dotnet test --no-restore --verbosity normal -f net48 --logger "trx;LogFileName=results4.trx" --filter Time!=Sensitive
-    - name: Upload test results (4.8)
-      uses: actions/upload-artifact@v4  # upload test results
-      if: success() || failure()        # run this step even if previous step failed
+    - name: Test pt1 (4.8)
+      run: dotnet test --no-restore --verbosity normal -f net48 --logger "trx;LogFileName=results4_1.trx" --filter Time!=Sensitive
+    - name: Upload test results pt1 (4.8)
+      uses: actions/upload-artifact@v4
+      if: success() || failure()
       with:
-          name: test-results-win48
-          path: BitFaster.Caching.UnitTests/TestResults/results4.trx
+          name: test-results-win48-pt1
+          path: BitFaster.Caching.UnitTests/TestResults/results4_1.trx
+
+    - name: Test pt2 (4.8)
+      run: dotnet test --no-restore --verbosity normal -f net48 --logger "trx;LogFileName=results4_2.trx" --filter Time=Sensitive
+    - name: Upload test results pt2 (4.8)
+      uses: actions/upload-artifact@v4
+      if: success() || failure()
+      with:
+          name: test-results-win48-pt2
+          path: BitFaster.Caching.UnitTests/TestResults/results4_2.trx
  
-    - name: Test (3.1)
-      run: dotnet test --no-restore --verbosity normal -f netcoreapp3.1 /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger "trx;LogFileName=results3.trx"  --filter Time!=Sensitive
+    - name: Test pt1 (3.1)
+      run: dotnet test --no-restore --verbosity normal -f netcoreapp3.1 /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger "trx;LogFileName=results3.trx" --filter Time!=Sensitive
+    - name: Upload test results pt1 (3.1)
+      uses: actions/upload-artifact@v4
+      if: success() || failure()
+      with:
+          name: test-results-win3-pt1
+          path: BitFaster.Caching.UnitTests/TestResults/results3.trx
+    - name: Publish coverage report pt1 to coveralls.io (3.1)
+      uses: coverallsapp/github-action@master   
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }} 
+        path-to-lcov: BitFaster.Caching.UnitTests/TestResults/coverage.netcoreapp3.1.info
+        flag-name: win3-pt1
+        parallel: true
+
+    - name: Test pt2 (3.1)
+      run: dotnet test --no-restore --verbosity normal -f netcoreapp3.1 /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger "trx;LogFileName=results3_2.trx"  --filter Time!=Sensitive
     - name: Upload test results (3.1)
       uses: actions/upload-artifact@v4  # upload test results
       if: success() || failure()        # run this step even if previous step failed
       with:
-          name: test-results-win3
-          path: BitFaster.Caching.UnitTests/TestResults/results3.trx
+          name: test-results-win3-pt2
+          path: BitFaster.Caching.UnitTests/TestResults/results3_2.trx
     - name: Publish coverage report to coveralls.io (3.1)
       uses: coverallsapp/github-action@master   
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }} 
         path-to-lcov: BitFaster.Caching.UnitTests/TestResults/coverage.netcoreapp3.1.info
-        flag-name: win3
+        flag-name: win3-pt2
         parallel: true
 
-    - name: Test (6.0)
-      run: dotnet test --no-restore --verbosity normal -f net6.0 /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger "trx;LogFileName=results6.trx" --filter Time!=Sensitive 
+    - name: Test pt1 (6.0)
+      run: dotnet test --no-restore --verbosity normal -f net6.0 /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger "trx;LogFileName=results6_1.trx" --filter Time!=Sensitive 
     - name: Upload test results (6.0)
       uses: actions/upload-artifact@v4  # upload test results
       if: success() || failure()        # run this step even if previous step failed
       with:
-          name: test-results-win6
-          path: BitFaster.Caching.UnitTests/TestResults/results6.trx
+          name: test-results-win6-pt1
+          path: BitFaster.Caching.UnitTests/TestResults/results6_1.trx
     - name: Upload test results (6.0 .NET Std)
       uses: actions/upload-artifact@v4
       if: success() || failure()
       with:
           name: test-results-win6-std
-          path: BitFaster.Caching.UnitTests.Std/TestResults/results6.trx
+          path: BitFaster.Caching.UnitTests.Std/TestResults/results6_1.trx
     
     - name: Publish coverage report to coveralls.io (6.0)
       uses: coverallsapp/github-action@master   
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }} 
         path-to-lcov: BitFaster.Caching.UnitTests/TestResults/coverage.net6.0.info
-        flag-name: win6
+        flag-name: win6-pt1
+        parallel: true
+
+    - name: Test pt2 (6.0)
+      run: dotnet test --no-restore --verbosity normal -f net6.0 /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger "trx;LogFileName=results6_2.trx" --filter Time=Sensitive 
+    - name: Upload test results (6.0)
+      uses: actions/upload-artifact@v4  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
+      with:
+          name: test-results-win6-pt2
+          path: BitFaster.Caching.UnitTests/TestResults/results6_2.trx
+
+    - name: Publish coverage report to coveralls.io (6.0)
+      uses: coverallsapp/github-action@master   
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }} 
+        path-to-lcov: BitFaster.Caching.UnitTests/TestResults/coverage.net6.0.info
+        flag-name: win6-pt2
         parallel: true
 
     - name: Publish NuGet artifacts
