test

diff --git a/.github/workflows/gate.yml b/.github/workflows/gate.yml
--- a/.github/workflows/gate.yml
+++ b/.github/workflows/gate.yml
@@ -31,15 +31,20 @@ jobs:
 
     - name: Test (4.8)
       run: dotnet test --no-restore --verbosity normal -f net48 --logger "trx;LogFileName=results4.trx"
-    - name: Generate unit test report (4.8)
-      uses: phoenix-actions/test-reporting@v15
-      id: unit-test-report-win48
-      if: success() || failure() 
+    - uses: actions/upload-artifact@v4  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
       with:
-        name: test results (win net4.8)
-        path: BitFaster.Caching.UnitTests/TestResults/results4.trx
-        reporter: dotnet-trx 
-        only-summary: 'true'
+          name: test-results4
+          path: BitFaster.Caching.UnitTests/TestResults/results4.trx
+#    - name: Generate unit test report (4.8)
+#      uses: phoenix-actions/test-reporting@v15
+#      id: unit-test-report-win48
+#      if: success() || failure() 
+#      with:
+#        name: test results (win net4.8)
+#        path: BitFaster.Caching.UnitTests/TestResults/results4.trx
+#        reporter: dotnet-trx 
+#        only-summary: 'true'
     
     - name: Test (3.1)
       run: dotnet test --no-restore --verbosity normal -f netcoreapp3.1 /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov --logger "trx;LogFileName=results3.trx"
